# Generated by Django 3.2.5 on 2021-08-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20210823_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
